// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoGKpVWpd6LHtkzSyt0Ql58Uy7vRrN6wE',
    appId: '1:1050649860152:web:f06fa538e3a0b13b13eecd',
    messagingSenderId: '1050649860152',
    projectId: 'ecommerce-shamo',
    authDomain: 'ecommerce-shamo.firebaseapp.com',
    storageBucket: 'ecommerce-shamo.appspot.com',
    measurementId: 'G-8WR1JKWYB2',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmL36vrUfV8IEqNPKzNYq3wKwGZiF_hjQ',
    appId: '1:1050649860152:android:6a5e5ba9248857ab13eecd',
    messagingSenderId: '1050649860152',
    projectId: 'ecommerce-shamo',
    storageBucket: 'ecommerce-shamo.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFhNN6_bddcb3_R7LOjSDYSKty-CCKQ1M',
    appId: '1:1050649860152:ios:612796111ce3b6fd13eecd',
    messagingSenderId: '1050649860152',
    projectId: 'ecommerce-shamo',
    storageBucket: 'ecommerce-shamo.appspot.com',
    iosBundleId: 'com.jerry.shamo',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFhNN6_bddcb3_R7LOjSDYSKty-CCKQ1M',
    appId: '1:1050649860152:ios:7717579dd94ca50113eecd',
    messagingSenderId: '1050649860152',
    projectId: 'ecommerce-shamo',
    storageBucket: 'ecommerce-shamo.appspot.com',
    iosBundleId: 'com.example.shamo',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoGKpVWpd6LHtkzSyt0Ql58Uy7vRrN6wE',
    appId: '1:1050649860152:web:155116a60658263413eecd',
    messagingSenderId: '1050649860152',
    projectId: 'ecommerce-shamo',
    authDomain: 'ecommerce-shamo.firebaseapp.com',
    storageBucket: 'ecommerce-shamo.appspot.com',
    measurementId: 'G-JCL6VENRL6',
  );
}
